# Generated by Django 4.1.2 on 2022-10-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
                ('day', models.CharField(blank=True, default='', max_length=200)),
                ('reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
